### ISSUE TITLE
Is this even updated?

### ISSUE THREAD

**Issue by Patriciawa** [SenseTecnic/node-red-contrib-users#13]
Is this even updated? I noticed that it uses bcrypt 2.0.1 while version 5..0.0. is available, you can't even download version 2.0.1 that's probably why I can't install this via npm as it requires bcrypt 2.0.1. When installing this manually it doesn't work. I am not getting any errors via the debug node. Anyone else having this?

**Comment by tedhuang** [comment]
Thank you for bringing this up. This has been fixed in the latest version on npm.

**Comment by Patriciawa** [comment]
Hi thanks for updating this!
However when going to the login screen I am getting a "Server error: oops.. something went wrong..." when clicking login
When adding a debug node it produces the following:
`"JWT cookie name is not set"
14-6-2020 00:33:16node: 6716707f.702fc
msg : string[33]`
`
"Deprecated call to msg.res.status"
14-6-2020 00:33:16node: d1826cb2.c615f
msg.payload : Object
{ empty }`
`
14-6-2020 00:33:16node: d1826cb2.c615f
msg.payload : Object
{ empty }`
`
14-6-2020 00:33:16node: fe64f419.139878
msg : error
`
`
"Error: Cannot set headers after they are sent to the client"`
Edit: it works now, guess I did something wrong.
