### ISSUE TITLE
Login via URL

### ISSUE THREAD

**Issue by kaizirlewagen** [SenseTecnic/node-red-contrib-users#14]
The module "node-red-contrib-users" works perfect. I used your demo to test it. But is it possible to login via URL?

https://ip-address:1880/demo?username=foo&password=bar

for example.

**Comment by tedhuang** [comment]
It doesn't support that currently. Sending in the credentials in the URL in plain text doesn't look very safe for security. It's definitely possible and you're welcome fork the repo and create your own support for it.
