### ISSUE TITLE
Uninstall doesn't remove users tab

### ISSUE THREAD

**Issue by dennishvo** [SenseTecnic/node-red-contrib-users#2]
I tried your package, but apparently msg.res.status no longer exists in 0.18.7. I tried to uninstall ("npm uninstall node-red-contrib-users") and the users tab is still there. You might add instructions about uninstalling. How do I fix this?

**Comment by adamalfath** [comment]
Same here. Need information how to remove the installation.

**Comment by tedhuang** [comment]
The node can be removed using the manage palette feature in Node-RED or by removing from the node_modules folder depending on how you've installed it. Getting an error with the msg.res.status should be indication that it wasn't configured properly.
