### ISSUE TITLE
Error upon npm install

### ISSUE THREAD

**Issue by rjdelbueno** [SenseTecnic/node-red-contrib-users#3]
Attempting to install via npm install I get the following errors:

pi@raspberrypi:~ $ npm install node-red-contrib-users

npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ node-red-contrib-users@0.1.7
updated 1 package in 5.476s

**Comment by Doom4535** [comment]
Do you still have this issue?  If so, what happens if you install using:

`sudo npm install --global node-red-contrib-users`

**Comment by tedhuang** [comment]
Install errors should have been fixed in the latest version.
