### ISSUE TITLE
not able to logout

### ISSUE THREAD

**Issue by eramirez405** [SenseTecnic/node-red-contrib-users#4]
I used the flow you provided as example. The login part is ok, although if I try to GET the users/logout what I get is "Cannot GET /users/logout" also if I got to /users the current user logged information is visible on the URL, the username and the password.

**Comment by ZCB1208** [comment]
At first, I was faced with the same problem. When I tried to empty clear cookie. Well,it works.

**Comment by ZCB1208** [comment]
At first, I was faced with the same problem. When I tried to clear cookie. Well,it works.

**Comment by DonatoD** [comment]
Hi, could someone please explain how to logout? I tried several way without success. So, once I login, even if I restart my computer, when I try again I'm already logged in.
This will help lots of people. I found a lot of request like mine but all without answers, A flow example will be very useful. There is no support on internet

**Comment by DonatoD** [comment]
this is what I see
![image](https://user-images.githubusercontent.com/51508670/77022849-f086f080-698a-11ea-98af-6a3166d0e9b5.png)
and this is what I get if I click on logout
![image](https://user-images.githubusercontent.com/51508670/77022915-1ad8ae00-698b-11ea-9849-9e795f159961.png)
and I'm still logged in

**Comment by tedhuang** [comment]
I can't seem to reproduce this. The log out handler essentially removes the JWT cookie from the browser used for authentication. If you cannot access the page then perhaps your httpNodeRoot is configured at a different endpoint.

**Comment by pdegior** [comment]
@DonatoD Were you able to resolve this.  We are having the same issue on a PC.  Installed the same setup on a Mac and it works perfectly.  Like yours, it isn't showing the nice formatted login form either.

**Comment by DonatoD** [comment]
No, unfortunately. At the end I gave up!

**Comment by johnnysbug** [comment]
The problem on windows is that `path.join` uses the operating system to determine separators. So, `path.join` in the `user.js` file is generating the wrong url path for logout (as well as missing styles). This should be using `path.posit.join` instead.

Observe:

![image](https://user-images.githubusercontent.com/1800439/102142447-0b0dcd80-3e28-11eb-9201-54b30765d951.png)

@tedhuang, are you accepting pull requests? I made one here: https://github.com/SenseTecnic/node-red-contrib-users/pull/18

@pdegior, this would fix our issue with logout on windows.
