### ISSUE TITLE
External user verification

### ISSUE THREAD

**Issue by Anniepoo** [SenseTecnic/node-red-contrib-users#6]
It would be useful to be able to verify a uname/pw/scope triple by some external  process, rather than having node-red-contrib-users  control the user list.

I propose two additional nodes, and a modification to the isloggedin node. 
Add a checkbox to the isloggedin node to use external verification
When this box is checked, instead of checking the node-red credentials cache, a message
will be emitted from a new wantsvalidate node. the flow writer will do something to validate the message, set a flag, and pass to a validate node.

This allows heterogenous systems to do things like check a database to confirm users.

**Comment by Anniepoo** [comment]
alternatively there could be a hook arranged for getUser. This might support further profile support, but would be less 'node-red' - ish

**Comment by tedhuang** [comment]
Similar with https://github.com/SenseTecnic/node-red-contrib-users/issues/12. Feature is technically possible but there are no further plans for this node at the moment. Forks and PRs are welcome.
